<?xml version="1.0"?>
<robot name="fusionrover" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:property name="chassis_mass"   value="10.0"/>
  <xacro:property name="chassis_length" value="0.45"/>
  <xacro:property name="chassis_width"  value="0.30"/>
  <xacro:property name="chassis_height" value="0.12"/>

  <xacro:property name="wheel_mass"   value="1.0"/>
  <xacro:property name="wheel_radius" value="0.06"/>
  <xacro:property name="wheel_width"  value="0.04"/>

  <xacro:property name="wheel_x_offset" value="0.18"/>
  <xacro:property name="wheel_y_offset" value="0.16"/>
  <xacro:property name="ground_clearance" value="0.02"/>

  <material name="gray">
    <color rgba="0.5 0.5 0.5 1.0"/>
  </material>
  <material name="black">
    <color rgba="0.0 0.0 0.0 1.0"/>
  </material>

  <link name="base_link">
    <visual>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
      <material name="gray"/>
    </visual>

    <collision>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
    </collision>

    <inertial>
      <mass value="${chassis_mass}"/>
      <origin xyz="0 0 0"/>
      <inertia
        ixx="${(1/12) * chassis_mass * (chassis_width*chassis_width + chassis_height*chassis_height)}"
        ixy="0.0" ixz="0.0"
        iyy="${(1/12) * chassis_mass * (chassis_length*chassis_length + chassis_height*chassis_height)}"
        iyz="0.0"
        izz="${(1/12) * chassis_mass * (chassis_length*chassis_length + chassis_width*chassis_width)}"/>
    </inertial>
  </link>

  <gazebo reference="base_link">
    <material>Gazebo/Grey</material>
  </gazebo>

  <xacro:macro name="wheel" params="name x y">
    <link name="${name}">
      <visual>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
        <origin xyz="0 0 0" rpy="1.5708 0 0"/>
        <material name="black"/>
      </visual>

      <collision>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
        <origin xyz="0 0 0" rpy="1.5708 0 0"/>
      </collision>

      <inertial>
        <mass value="${wheel_mass}"/>
        <inertia
          ixx="${(1/12)*wheel_mass*(3*wheel_radius*wheel_radius + wheel_width*wheel_width)}"
          ixy="0.0" ixz="0.0"
          iyy="${(1/12)*wheel_mass*(3*wheel_radius*wheel_radius + wheel_width*wheel_width)}"
          iyz="0.0"
          izz="${(1/2)*wheel_mass*(wheel_radius*wheel_radius)}"/>
      </inertial>
    </link>

    <joint name="${name}_joint" type="continuous">
      <parent link="base_link"/>
      <child link="${name}"/>
      <origin xyz="${x} ${y} ${-(chassis_height/2 + ground_clearance - wheel_radius)}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
    </joint>

    <gazebo reference="${name}">
      <material>Gazebo/Black</material>
      <mu1 value="1.0"/>
      <mu2 value="1.0"/>
    </gazebo>
  </xacro:macro>

  <xacro:wheel name="front_left_wheel"  x="${wheel_x_offset}"  y="${wheel_y_offset}"/>
  <xacro:wheel name="front_right_wheel" x="${wheel_x_offset}"  y="-${wheel_y_offset}"/>
  <xacro:wheel name="rear_left_wheel"   x="-${wheel_x_offset}" y="${wheel_y_offset}"/>
  <xacro:wheel name="rear_right_wheel"  x="-${wheel_x_offset}" y="-${wheel_y_offset}"/>

</robot>